version: '3.4'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    user: ${UID:-app}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static-build:/tmp/static-build
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - SECRET_KEY=59114b6a-2858-4caf-8878-482a24ee9542
      - PG_NAME=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=db
      - PG_PORT=5432 
    command:
      ./bin/run-dev.sh
