version: '3.4'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    user: ${UID:-app}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - DATABASE_URL=sqlite:///database.sqlite
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - SECRET_KEY=59114b6a-2858-4caf-8878-482a24ee9542
    command:
      ./bin/run-dev.sh
